const ENERMY_BASE_COUNT = 5
const ENERMY_INCREMENT_RATIO = 1.3

// 玩家生命值配置
const PLAYER_MAX_HP = 100
const PLAYER_INVINCIBLE_TIME = 1.5 // 受伤后无敌时间（秒）

// 敌人攻击力配置
const ENEMY_ATTACK = {
  DEFAULT: 20,
  ENEMY_22: 15,
  ENEMY_33: 25,
  FIREBALL: 30
}

export {
  ENERMY_BASE_COUNT,
  ENERMY_INCREMENT_RATIO,
  PLAYER_MAX_HP,
  PLAYER_INVINCIBLE_TIME,
  ENEMY_ATTACK
}
