// 敌人生成配置
const ENERMY_BASE_COUNT = 5
const ENERMY_INCREMENT_RATIO = 1.3
const GEN_ENEMY_INTERVAL = 0.5 // 敌人生成间隔（秒）
const ENEMIES_PER_SPAWN = 3 // 每次生成敌人数量

// 游戏进度配置
const DEFAULT_LEVEL = 1
const DEFAULT_SCORE = 0
const SCORE_PER_LEVEL = 100 // 每100分升一级

export {
  ENERMY_BASE_COUNT,
  ENERMY_INCREMENT_RATIO,
  GEN_ENEMY_INTERVAL,
  ENEMIES_PER_SPAWN,
  DEFAULT_LEVEL,
  DEFAULT_SCORE,
  SCORE_PER_LEVEL
}
