import * as weapon from '../sprites.weapon'
import { Sprite } from '../../../core/sprite'
import { Weapon, WeaponType } from '../sprites.weapon'
import { bitmapsToTextures } from '../../../core/utils'

const WIDTH = 8
const HEIGHT = 8
const HP = 1

const COLOR_MAP: TColorMap = {
  '0': 'transparent',
  '1': '#6dc2ca',
  '2': '#deeed6'
}

const BITMAPS: TBitmaps = [
  [
    '0', '0', '1', '0', '0', '1', '0', '0',
    '0', '0', '0', '1', '1', '0', '0', '0',
    '1', '1', '1', '1', '1', '1', '1', '1',
    '1', '2', '2', '2', '2', '2', '2', '1',
    '1', '2', '1', '2', '2', '1', '2', '1',
    '1', '2', '1', '2', '2', '1', '2', '1',
    '1', '2', '2', '2', '2', '2', '2', '1',
    '1', '1', '1', '1', '1', '1', '1', '1',
  ]
]

class SmallTV extends Sprite {
  width = WIDTH
  height = HEIGHT
  textures = bitmapsToTextures(WIDTH, HEIGHT, BITMAPS, COLOR_MAP)

  /**
   * Weapons which are generated by this player.
   *
   * @type {Weapon[]}
   * @memberof SmallTV
   */
  weapons: Weapon[] = []

  /**
   * Current count of weapons.
   *
   * @type {number}
   * @memberof SmallTV
   */
  weaponCount: number = 0

  /**
   * Weapon direction.
   *
   * @type {TDirection}
   * @memberof SmallTV
   */
  weaponDirection: TDirection = null

  /**
   * Current weapon availablity countdown.
   *
   * @type {number}
   * @memberof SmallTV
   */
  weaponCountdown: number = 0

  /**
   * Current weapon class.
   *
   * @type {Sprite}
   * @memberof SmallTV
   */
  currentWeaponClass = null

  /**
   * Current weapon type.
   *
   * @type {WeaponType}
   * @memberof SmallTV
   */
  currentWeaponType: WeaponType = WeaponType.BULLET

  /**
   * Weapon duration countdown (for special weapons).
   * When this reaches 0, weapon reverts to default.
   *
   * @type {number}
   * @memberof SmallTV
   */
  weaponDuration: number = 0

  /**
   * Attacking status.
   *
   * @type {boolean}
   * @memberof SmallTV
   */
  attacking: boolean = false

  /**
   * Is dead?
   *
   * @type {boolean}
   * @memberof SmallTV
   */
  isDead: boolean = false

  /**
   * Switch to a new weapon type.
   *
   * @param {WeaponType} type
   * @param {number} duration - Duration in seconds (0 = permanent)
   * @param {boolean} additive - If true, add duration to existing time
   * @memberof SmallTV
   */
  switchWeapon (type: WeaponType, duration: number = 0, additive: boolean = false) {
    // 如果是同类型武器且叠加模式，累加时间
    if (additive && this.currentWeaponType === type) {
      this.weaponDuration += duration
    } else {
      // 切换不同武器时，保留较大的时间
      this.currentWeaponType = type
      this.weaponDuration = Math.max(this.weaponDuration, duration)
    }

    switch (type) {
      case WeaponType.POWER_BULLET:
        this.currentWeaponClass = weapon.PowerBullet
        break
      case WeaponType.SHOTGUN:
        this.currentWeaponClass = null  // Shotgun handled specially
        break
      case WeaponType.BULLET:
      default:
        this.currentWeaponClass = weapon.Bullet
        break
    }
  }

  /**
   * Tick weapon duration and revert to default if expired.
   *
   * @param {number} deltaTime - Time elapsed in seconds
   * @memberof SmallTV
   */
  tickWeaponDuration (deltaTime: number) {
    if (this.weaponDuration > 0) {
      this.weaponDuration -= deltaTime
      if (this.weaponDuration <= 0) {
        this.switchWeapon(WeaponType.BULLET)
      }
    }
  }

  constructor () {
    super()
    this.x = 0
    this.y = 0
    this.hp = HP
    this.speed = 1
    this.paddingX = 1  // 缩小左右碰撞区域
    this.paddingY = 2  // 顶部天线不算碰撞区域
    this.isDead = false

    // Unique props of player type.
    this.weaponCount = 1
    this.weaponDirection = 'L'
    this.weaponCountdown = 0
    this.currentWeaponClass = weapon.Bullet
    this.currentWeaponType = WeaponType.BULLET
    this.weaponDuration = 0

    this.TEXTURE_CHANGING_COUNTDOWN = false
  }
}

export {
  SmallTV
}
