import { Sprite } from '../../../core/sprite'
import { SpriteColorMap, SpriteBitmaps, SpriteDirection } from '../../../core/sprite/types.ts'
import { bitmapsToTextures } from '../../../core/utils'
import { WeaponBase } from '../weapon/defines/_base.ts'
import { Bullet } from '../weapon/defines/bullet.ts'
import { PowerBullet } from '../weapon/defines/power-bullet.ts'
import { WeaponType } from '../weapon/types.ts'

const WIDTH = 8
const HEIGHT = 8
const HP = 1

const COLOR_MAP: SpriteColorMap = {
  0: 'transparent',
  1: '#6dc2ca',
  2: '#deeed6'
}

const BITMAPS: SpriteBitmaps = [
  [
    '0', '0', '1', '0', '0', '1', '0', '0',
    '0', '0', '0', '1', '1', '0', '0', '0',
    '1', '1', '1', '1', '1', '1', '1', '1',
    '1', '2', '2', '2', '2', '2', '2', '1',
    '1', '2', '1', '2', '2', '1', '2', '1',
    '1', '2', '1', '2', '2', '1', '2', '1',
    '1', '2', '2', '2', '2', '2', '2', '1',
    '1', '1', '1', '1', '1', '1', '1', '1'
  ]
]

class SmallTV extends Sprite {
  width = WIDTH
  height = HEIGHT
  textures = bitmapsToTextures(WIDTH, HEIGHT, BITMAPS, COLOR_MAP)

  /**
   * Weapons which are generated by this player.
   *
   * @type {WeaponBase[]}
   * @memberof SmallTV
   */
  weapons: WeaponBase[] = []

  /**
   * Current count of weapons.
   *
   * @type {number}
   * @memberof SmallTV
   */
  weaponCount: number = 0

  /**
   * Weapon direction.
   *
   * @type {SpriteDirection}
   * @memberof SmallTV
   */
  weaponDirection: SpriteDirection = null

  /**
   * Current weapon availablity countdown.
   *
   * @type {number}
   * @memberof SmallTV
   */
  weaponCountdown: number = 0

  /**
   * Current weapon class.
   *
   * @type {Sprite}
   * @memberof SmallTV
   */
  currentWeaponClass = null

  /**
   * Current weapon type.
   *
   * @type {WeaponType}
   * @memberof SmallTV
   */
  currentWeaponType: WeaponType = WeaponType.BULLET

  /**
   * Weapon duration countdown (for special weapons).
   * When this reaches 0, weapon reverts to default.
   *
   * @type {number}
   * @memberof SmallTV
   */
  weaponDuration: number = 0

  /**
   * Attacking status.
   *
   * @type {boolean}
   * @memberof SmallTV
   */
  attacking: boolean = false

  /**
   * Is dead?
   *
   * @type {boolean}
   * @memberof SmallTV
   */
  isDead: boolean = false

  /**
   * Analog movement values from gamepad.
   * Range: -1.0 to 1.0
   *
   * @type {number}
   * @memberof SmallTV
   */
  analogMoveX: number = 0
  analogMoveY: number = 0

  /**
   * 右摇杆射击角度（弧度）
   * 用于无极方向射击
   * null 表示使用键盘的四方向模式
   */
  shootAngle: number | null = null

  /**
   * 是否使用摇杆的无极射击模式
   */
  useAnalogShooting: boolean = false

  /**
   * Switch to a new weapon type.
   *
   * @param {WeaponType} type
   * @param {number} duration - Duration in seconds (0 = permanent)
   * @param {boolean} additive - If true, add duration to existing time
   * @memberof SmallTV
   */
  switchWeapon (type: WeaponType, duration: number = 0, additive: boolean = false) {
    // 叠加模式：无论什么道具都累加时间，然后切换为新武器
    if (additive) {
      this.weaponDuration += duration
    } else {
      // 非叠加模式：直接设置时间
      this.weaponDuration = duration
    }

    // 切换到新的武器类型
    this.currentWeaponType = type

    switch (type) {
      case WeaponType.POWER_BULLET:
        this.currentWeaponClass = PowerBullet
        break
      case WeaponType.SHOTGUN:
        this.currentWeaponClass = null // Shotgun handled specially
        break
      case WeaponType.BULLET:
      default:
        this.currentWeaponClass = Bullet
        break
    }
  }

  /**
   * Tick weapon duration and revert to default if expired.
   *
   * @param {number} deltaTime - Time elapsed in seconds
   * @memberof SmallTV
   */
  tickWeaponDuration (deltaTime: number) {
    if (this.weaponDuration > 0) {
      this.weaponDuration -= deltaTime
      if (this.weaponDuration <= 0) {
        this.switchWeapon(WeaponType.BULLET)
      }
    }
  }

  constructor () {
    super()
    this.x = 0
    this.y = 0
    this.hp = HP
    this.speed = 1
    this.paddingX = 1 // 缩小左右碰撞区域
    this.paddingY = 2 // 顶部天线不算碰撞区域
    this.isDead = false

    // Unique props of player type.
    this.weaponCount = 1
    this.weaponDirection = 'L'
    this.weaponCountdown = 0
    this.currentWeaponClass = Bullet
    this.currentWeaponType = WeaponType.BULLET
    this.weaponDuration = 0

    this.TEXTURE_CHANGING_COUNTDOWN = false
  }
}

export {
  SmallTV
}
