import { Sprite } from '../../../core/sprite'
import { SpriteColorMap, SpriteBitmap, SpriteDirection } from '../../../core/sprite/types.ts'
import { bitmapsToTextures } from '../../../core/utils'
import { Bullet } from '../weapon/defines/bullet.ts'
import { Laser } from '../weapon/defines/laser.ts'
import { PowerBullet } from '../weapon/defines/power-bullet.ts'
import { WeaponType } from '../weapon/types.ts'
import { WeaponBase } from '../weapon/weapon-base.ts'

const PLAYER_INITIAL_HP = 100
const PLAYER_INVINCIBLE_TIME = 1.5 // 受伤后无敌时间（秒）
const SHIELD_DURATION = 5 // 护盾持续时间（秒）
const SPEED_BUFF_DURATION = 8 // 加速持续时间（秒）
const SPEED_BUFF_MULTIPLIER = 1.8 // 加速倍率

const WIDTH = 8
const HEIGHT = 8

const COLOR_MAP: SpriteColorMap = {
  0: 'transparent',
  1: '#6dc2ca',
  2: '#deeed6'
}

// 默认状态（眼睛居中）
const BITMAP_DEFAULT: SpriteBitmap = [
  '0', '0', '1', '0', '0', '1', '0', '0',
  '0', '0', '0', '1', '1', '0', '0', '0',
  '1', '1', '1', '1', '1', '1', '1', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '2', '1', '2', '2', '1', '2', '1',
  '1', '2', '1', '2', '2', '1', '2', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '1', '1', '1', '1', '1', '1', '1'
]

// 向左看（天线+眼睛左移）
const BITMAP_LEFT: SpriteBitmap = [
  '0', '1', '0', '0', '1', '0', '0', '0',
  '0', '0', '1', '1', '0', '0', '0', '0',
  '1', '1', '1', '1', '1', '1', '1', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '1', '2', '2', '1', '2', '2', '1',
  '1', '1', '2', '2', '1', '2', '2', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '1', '1', '1', '1', '1', '1', '1'
]

// 向右看（天线+眼睛右移）
const BITMAP_RIGHT: SpriteBitmap = [
  '0', '0', '0', '1', '0', '0', '1', '0',
  '0', '0', '0', '0', '1', '1', '0', '0',
  '1', '1', '1', '1', '1', '1', '1', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '2', '2', '1', '2', '2', '1', '1',
  '1', '2', '2', '1', '2', '2', '1', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '1', '1', '1', '1', '1', '1', '1'
]

// 向上看（眼睛上移）
const BITMAP_UP: SpriteBitmap = [
  '0', '0', '1', '0', '0', '1', '0', '0',
  '0', '0', '0', '1', '1', '0', '0', '0',
  '1', '1', '1', '1', '1', '1', '1', '1',
  '1', '2', '1', '2', '2', '1', '2', '1',
  '1', '2', '1', '2', '2', '1', '2', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '1', '1', '1', '1', '1', '1', '1'
]

// 向下看（眼睛下移）
const BITMAP_DOWN: SpriteBitmap = [
  '0', '0', '1', '0', '0', '1', '0', '0',
  '0', '0', '0', '1', '1', '0', '0', '0',
  '1', '1', '1', '1', '1', '1', '1', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '2', '2', '2', '2', '2', '2', '1',
  '1', '2', '1', '2', '2', '1', '2', '1',
  '1', '2', '1', '2', '2', '1', '2', '1',
  '1', '1', '1', '1', '1', '1', '1', '1'
]

// 按方向索引的纹理映射（T=Top/上, B=Bottom/下, L=Left/左, R=Right/右）
const DIRECTION_TEXTURES: Record<string, ImageData[]> = {
  L: bitmapsToTextures(WIDTH, HEIGHT, [BITMAP_LEFT], COLOR_MAP),
  R: bitmapsToTextures(WIDTH, HEIGHT, [BITMAP_RIGHT], COLOR_MAP),
  T: bitmapsToTextures(WIDTH, HEIGHT, [BITMAP_UP], COLOR_MAP),
  B: bitmapsToTextures(WIDTH, HEIGHT, [BITMAP_DOWN], COLOR_MAP),
  default: bitmapsToTextures(WIDTH, HEIGHT, [BITMAP_DEFAULT], COLOR_MAP)
}

class SmallTV extends Sprite {
  width = WIDTH
  height = HEIGHT
  textures = DIRECTION_TEXTURES.default

  /** 当前显示方向 */
  private currentLookDirection: SpriteDirection = null

  // ==========================================
  // Roguelike Upgrade Stats
  // ==========================================

  /** 伤害倍率 (1.0 = 100%) */
  damageMultiplier: number = 1.0

  /** 速度倍率 (1.0 = 100%) */
  speedMultiplier: number = 1.0

  /** 射速倍率 (1.0 = 100%) */
  fireRateMultiplier: number = 1.0

  /** 护甲 - 减少受到的伤害 */
  armor: number = 0

  /** 生命回复 - 每秒恢复的HP */
  hpRegen: number = 0

  /** 经验值倍率 */
  xpMultiplier: number = 1.0

  /** 暴击率 (0-1) */
  critChance: number = 0

  /** 暴击伤害倍率 */
  critDamage: number = 1.5

  /** 闪避率 (0-1) */
  dodgeChance: number = 0

  /** 物品吸引范围 */
  magnetRange: number = 0

  // 武器特殊效果
  /** 双发射击 */
  hasDoubleShot: boolean = false

  /** 三发散射 */
  hasTripleShot: boolean = false

  /** 后方射击 */
  hasRearShot: boolean = false

  /** 穿透射击 */
  hasPiercing: boolean = false

  /** 吸血效果 */
  hasLifesteal: boolean = false

  /** 击杀爆炸 */
  hasExplosionOnKill: boolean = false

  /** 升级时获得护盾 */
  hasShieldOnLevel: boolean = false

  /**
   * Weapons which are generated by this player.
   *
   * @type {WeaponBase[]}
   * @memberof SmallTV
   */
  weapons: WeaponBase[] = []

  /**
   * Current count of weapons.
   *
   * @type {number}
   * @memberof SmallTV
   */
  weaponCount: number = 0

  /**
   * Weapon direction.
   *
   * @type {SpriteDirection}
   * @memberof SmallTV
   */
  weaponDirection: SpriteDirection = null

  /**
   * Current weapon availablity countdown.
   *
   * @type {number}
   * @memberof SmallTV
   */
  weaponCountdown: number = 0

  /**
   * Current weapon class.
   *
   * @type {Sprite}
   * @memberof SmallTV
   */
  currentWeaponClass = null

  /**
   * Current weapon type.
   *
   * @type {WeaponType}
   * @memberof SmallTV
   */
  currentWeaponType: WeaponType = WeaponType.BULLET

  /**
   * Weapon duration countdown (for special weapons).
   * When this reaches 0, weapon reverts to default.
   *
   * @type {number}
   * @memberof SmallTV
   */
  weaponDuration: number = 0

  /**
   * Attacking status.
   *
   * @type {boolean}
   * @memberof SmallTV
   */
  attacking: boolean = false

  /**
   * 玩家最大生命值
   *
   * @type {number}
   * @memberof SmallTV
   */
  maxHp: number = PLAYER_INITIAL_HP

  /**
   * 无敌时间剩余（秒）
   *
   * @type {number}
   * @memberof SmallTV
   */
  invincibleTimer: number = 0

  /**
   * 是否处于无敌状态
   *
   * @readonly
   * @type {boolean}
   * @memberof SmallTV
   */
  get isInvincible (): boolean {
    return this.invincibleTimer > 0 || this.shieldTimer > 0
  }

  /**
   * 护盾时间剩余（秒）
   *
   * @type {number}
   * @memberof SmallTV
   */
  shieldTimer: number = 0

  /**
   * 护盾可承受的攻击次数（升级护盾）
   *
   * @type {number}
   * @memberof SmallTV
   */
  shieldHits: number = 0

  /**
   * 是否有护盾（时间护盾或次数护盾）
   *
   * @readonly
   * @type {boolean}
   * @memberof SmallTV
   */
  get hasShield (): boolean {
    return this.shieldTimer > 0 || this.shieldHits > 0
  }

  /**
   * 设置护盾状态
   * @param value - 是否有护盾
   */
  set hasShield (value: boolean) {
    // 当设置为 true 时，如果没有其他护盾，设置 shieldHits = 1
    if (value && !this.hasShield) {
      this.shieldHits = 1
    } else if (!value) {
      this.shieldHits = 0
      this.shieldTimer = 0
    }
  }

  /**
   * 速度加成时间剩余（秒）
   *
   * @type {number}
   * @memberof SmallTV
   */
  speedBuffTimer: number = 0

  /**
   * 是否有速度加成
   *
   * @readonly
   * @type {boolean}
   * @memberof SmallTV
   */
  get hasSpeedBuff (): boolean {
    return this.speedBuffTimer > 0
  }

  /**
   * 获取当前有效速度（考虑永久加成和临时加成）
   */
  getEffectiveSpeed (): number {
    let speed = this.speed * this.speedMultiplier
    if (this.hasSpeedBuff) {
      speed *= SPEED_BUFF_MULTIPLIER
    }
    return speed
  }

  /**
   * 获取有效武器冷却时间（考虑射速加成）
   * fireRateMultiplier 越高，冷却越短
   */
  getEffectiveFireRate (baseInterval: number): number {
    return baseInterval / this.fireRateMultiplier
  }

  /**
   * 获取有效伤害值（考虑伤害加成和暴击）
   */
  getEffectiveDamage (baseDamage: number): number {
    let damage = baseDamage * this.damageMultiplier

    // 暴击判定
    if (this.critChance > 0 && Math.random() < this.critChance) {
      damage *= this.critDamage
    }

    return Math.floor(damage)
  }

  /**
   * Is dead?
   *
   * @readonly
   * @type {boolean}
   * @memberof SmallTV
   */
  get isDead (): boolean {
    return this.hp <= 0
  }

  /**
   * Analog movement values from gamepad.
   * Range: -1.0 to 1.0
   *
   * @type {number}
   * @memberof SmallTV
   */
  analogMoveX: number = 0
  analogMoveY: number = 0

  /**
   * 右摇杆射击角度（弧度）
   * 用于无极方向射击
   * null 表示使用键盘的四方向模式
   */
  shootAngle: number | null = null

  /**
   * 是否使用摇杆的无极射击模式
   */
  useAnalogShooting: boolean = false

  /**
   * Switch to a new weapon type.
   *
   * @param {WeaponType} type
   * @param {number} duration - Duration in seconds (0 = permanent)
   * @param {boolean} additive - If true, add duration to existing time
   * @memberof SmallTV
   */
  switchWeapon (type: WeaponType, duration: number = 0, additive: boolean = false) {
    // 叠加模式：无论什么道具都累加时间，然后切换为新武器
    if (additive) {
      this.weaponDuration += duration
    } else {
      // 非叠加模式：直接设置时间
      this.weaponDuration = duration
    }

    // 切换到新的武器类型
    this.currentWeaponType = type

    switch (type) {
      case WeaponType.POWER_BULLET:
        this.currentWeaponClass = PowerBullet
        break
      case WeaponType.SHOTGUN:
        this.currentWeaponClass = null // Shotgun handled specially
        break
      case WeaponType.LASER:
        this.currentWeaponClass = Laser
        break
      case WeaponType.BULLET:
      default:
        this.currentWeaponClass = Bullet
        break
    }
  }

  /**
   * Tick weapon duration and revert to default if expired.
   *
   * @param {number} deltaTime - Time elapsed in seconds
   * @memberof SmallTV
   */
  tickWeaponDuration (deltaTime: number) {
    if (this.weaponDuration > 0) {
      this.weaponDuration -= deltaTime
      if (this.weaponDuration <= 0) {
        this.switchWeapon(WeaponType.BULLET)
      }
    }
  }

  /**
   * 受到伤害（考虑护盾、闪避和护甲）
   *
   * @param {number} damage - 伤害值
   * @returns {boolean} - 是否实际受到了伤害
   * @memberof SmallTV
   */
  takeDamage (damage: number): boolean {
    if (this.isInvincible || this.isDead) {
      return false
    }

    // 护盾判定（优先消耗护盾）
    if (this.hasShield) {
      // 优先消耗次数护盾
      if (this.shieldHits > 0) {
        this.shieldHits--
      } else {
        // 消耗时间护盾
        this.shieldTimer = 0
      }
      // 护盾抵消伤害，进入无敌状态
      this.invincibleTimer = PLAYER_INVINCIBLE_TIME
      return false
    }

    // 闪避判定
    if (this.dodgeChance > 0 && Math.random() < this.dodgeChance) {
      // 闪避成功！不受伤害
      return false
    }

    // 护甲减伤（每点护甲减少1点伤害，最少受到1点）
    const actualDamage = Math.max(1, damage - this.armor)

    this.hp -= actualDamage
    if (this.hp < 0) {
      this.hp = 0
    }
    // 受伤后进入无敌状态
    if (!this.isDead) {
      this.invincibleTimer = PLAYER_INVINCIBLE_TIME
    }
    return true
  }

  /**
   * 更新无敌状态计时器
   *
   * @param {number} deltaTime - 时间增量（秒）
   * @memberof SmallTV
   */
  tickInvincible (deltaTime: number) {
    if (this.invincibleTimer > 0) {
      this.invincibleTimer -= deltaTime
      if (this.invincibleTimer < 0) {
        this.invincibleTimer = 0
      }
    }
    if (this.shieldTimer > 0) {
      this.shieldTimer -= deltaTime
      if (this.shieldTimer < 0) {
        this.shieldTimer = 0
      }
    }
    if (this.speedBuffTimer > 0) {
      this.speedBuffTimer -= deltaTime
      if (this.speedBuffTimer < 0) {
        this.speedBuffTimer = 0
      }
    }
  }

  /**
   * 激活护盾
   *
   * @param {boolean} additive - 是否叠加时间
   * @memberof SmallTV
   */
  activateShield (additive: boolean = true) {
    if (additive) {
      this.shieldTimer += SHIELD_DURATION
    } else {
      this.shieldTimer = SHIELD_DURATION
    }
  }

  /**
   * 激活速度加成
   *
   * @param {boolean} additive - 是否叠加时间
   * @memberof SmallTV
   */
  activateSpeedBuff (additive: boolean = true) {
    if (additive) {
      this.speedBuffTimer += SPEED_BUFF_DURATION
    } else {
      this.speedBuffTimer = SPEED_BUFF_DURATION
    }
  }

  /**
   * 重置玩家状态（用于重新开始游戏）
   *
   * @memberof SmallTV
   */
  reset () {
    // 基础属性
    this.hp = PLAYER_INITIAL_HP
    this.maxHp = PLAYER_INITIAL_HP
    this.invincibleTimer = 0
    this.shieldTimer = 0
    this.shieldHits = 0
    this.speedBuffTimer = 0
    this.weaponDuration = 0
    this.currentWeaponType = WeaponType.BULLET
    this.currentWeaponClass = Bullet

    // Roguelike 升级属性重置
    this.damageMultiplier = 1.0
    this.speedMultiplier = 1.0
    this.fireRateMultiplier = 1.0
    this.armor = 0
    this.hpRegen = 0
    this.xpMultiplier = 1.0
    this.critChance = 0
    this.critDamage = 1.5
    this.dodgeChance = 0
    this.magnetRange = 0

    // 武器特殊效果重置
    this.hasDoubleShot = false
    this.hasTripleShot = false
    this.hasRearShot = false
    this.hasPiercing = false
    this.hasLifesteal = false
    this.hasExplosionOnKill = false
    this.hasShieldOnLevel = false
  }

  /**
   * 根据射击方向更新外观
   * 调用此方法时会根据 weaponDirection 切换纹理
   */
  updateLookDirection () {
    if (this.weaponDirection === this.currentLookDirection) {
      return // 方向没变，不需要更新
    }

    this.currentLookDirection = this.weaponDirection

    const direction = this.weaponDirection || 'default'
    const newTextures = DIRECTION_TEXTURES[direction] || DIRECTION_TEXTURES.default

    if (this.textures !== newTextures) {
      this.textures = newTextures
      // 强制刷新：直接把新纹理画到 offscreen
      if (this.offscreen && this.textures[0]) {
        this.offscreen.context.putImageData(this.textures[0], 0, 0)
      }
    }
  }

  constructor () {
    super('player')
    this.x = 0
    this.y = 0
    this.hp = PLAYER_INITIAL_HP
    this.speed = 60
    this.paddingX = 1 // 缩小左右碰撞区域
    this.paddingY = 2 // 顶部天线不算碰撞区域

    // Unique props of player type.
    this.weaponCount = 1
    this.weaponDirection = 'L'
    this.weaponCountdown = 0
    this.currentWeaponClass = Bullet
    this.currentWeaponType = WeaponType.BULLET
    this.weaponDuration = 0

    this.TEXTURE_CHANGING_COUNTDOWN = false

    // 初始化时使用默认居中外观（还没射击）
    this.currentLookDirection = null
    this.textures = DIRECTION_TEXTURES.default
  }
}

export {
  SmallTV
}
